/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 09 01:42:56 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Oddevepri_ESTest extends Oddevepri_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = 1288;
      Oddevepri.odd(1288);
      Oddevepri.odd(0);
      int int1 = 1823;
      // Undeclared exception!
      Oddevepri.prime(1823);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Oddevepri.odd(1563);
      Oddevepri.even(1563);
      Oddevepri.odd(0);
      Oddevepri.odd(0);
      Oddevepri.odd(0);
      Oddevepri.even((-175));
      Oddevepri.odd(1165);
      Oddevepri.even(1);
      Oddevepri.odd(0);
      Oddevepri oddevepri0 = new Oddevepri();
      Oddevepri.odd(1563);
      Oddevepri.even(1165);
      Oddevepri.even(1165);
      Oddevepri.prime(0);
      Oddevepri.prime(1);
      Oddevepri.prime(0);
      Oddevepri.even(1);
      Oddevepri.even(0);
      Oddevepri.prime((-175));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Oddevepri.odd(3574);
      Oddevepri.odd((-2724));
      Oddevepri oddevepri0 = new Oddevepri();
      Oddevepri.even(0);
      Oddevepri.odd(4452);
      Oddevepri.prime(0);
      // Undeclared exception!
      Oddevepri.odd(3574);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Oddevepri.even(5611);
      Oddevepri oddevepri0 = new Oddevepri();
      Oddevepri.odd(5611);
      // Undeclared exception!
      Oddevepri.even(5611);
  }
}
